name: production_code__c
data_type: text
filterable: false
formula: product__c.production_code__c
formula_blank_value: blanks
hidden: false
index: false
is_name: false
is_wide: false
label: 生产编码
omit: false
readonly: false
required: false
searchable: false
sort_no: 130
sortable: false
type: formula
