name: product_type_new__c
group: 校验信息
label: 新产品分类
multiple: true
options:
  - label: 新产品分类1
    value: 新产品分类1
  - label: 新产品分类2
    value: 新产品分类2
  - label: 新产品分类3
    value: 新产品分类3
sort_no: 180
type: select
